name: YansFood Landing Page CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t yansfood_landing:latest .

    - name: Tag docker image
      run: docker tag yansfood_landing:latest etie20/yansfood_landing:latest

    - name: Push Docker image to Docker Hub
      run: docker push etie20/yansfood_landing:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        name: Deploy the application
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd yansfood
            docker-compose down
            docker-compose pull
            docker-compose up -d
